### ISSUE TITLE
KDevelop fails to run due to error

### ISSUE THREAD

**Issue by whytiwari** [flathub/org.kde.kdevelop#9]
The new update breaks Kdevelop and running it results in this error:

```
bwrap: Can't mkdir parents for /app/usr/lib/sdk/llvm12: Read-only file system
error: ldconfig failed, exit status 256
```

I've tried running flatpak repair and the problem still persists.

Flatpak Version - 1.12.4
Fedora Kinoite

**Comment by tsdgeos** [comment]
@travier any idea about this? Seems more an llvm12 extension issue?

**Comment by travier** [comment]
That's extra weird, this happens during Flatpak env setup as I can not even get a shell in the Flatpak. Nothing stands out as there have not been any change in the extension recently and the changes here are only for Kdevelop itself.

**Comment by travier** [comment]
This weirdly runs when I build it locally but not when I run it from Flathub 😕

**Comment by Eoin-ONeill-Yokai** [comment]
I'm having this issue as well. Does anyone know if rolling back a version or two is an option?

**Comment by travier** [comment]
https://github.com/flathub/org.kde.kdevelop/pull/12 > This should has the fix. Will merge once the build succeeds.

**Comment by Eoin-ONeill-Yokai** [comment]
@travier Thank you! Just updated and it's working great.
